version: '3.3'
services:
  db:
    container_name: mongo
    networks: 
      - red
    volumes:
      - 'mi-volumen:/data/db'
    image: 'mongo:latest'
  web:
    container_name: node
    env_file: .env
    networks: 
      - red
    build: .
  front:
    container_name: react
    networks: 
      - red
    ports: 
      - "80:80"
    build: 
      context: frontend

networks: 
  red:
volumes: 
  mi-volumen: