apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-uploads-1
  namespace: mern
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
  namespace: mern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: us.gcr.io/proyecto-gen2/node-back-1
        env:
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "8080"
        - name: MONGO_URI
          value: "mongodb://mi-servicio-mongo.mern.svc.cluster.local:27017"
        - name: JWT_SECRET
          value: "123dfg5"
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: vol
            mountPath: /usr/src/app/uploads
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: pvc-uploads-1
    
---

apiVersion: v1
kind: Service
metadata:
  name: mi-servicio-node
  namespace: mern  
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP